services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: traduca
      MYSQL_ROOT_PASSWORD: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]
    networks:
      - laravel

  node:
    image: node:22-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    entrypoint: ["sh", "-c"]
    command: "npm install && npm run dev -- --host"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge